version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "emart-account-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qlcxpo3sc6q4"
s3_prefix = "emart-account-app"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

